---
title: "CC_mapping_example"
author: "John R Shorter"
date: "June 13, 2019"
output: html_document
---

```{r setup, include=FALSE}
setwd("C:/Users/John/Desktop/mapping")
```

```{r}
library(abind)
library(RSQLite)
library(doBy)
library(DOQTL)

## load other libraries, including argyle and mouser from Andrew Morgan
library(ggplot2)
library(plyr)
library(qtl2)
library(qtl2convert)

```


```{r}
#Collapse into 8 state. Only need to do once!!
##Pull from http://csbio.unc.edu/CCstatus/index.py?run=FounderProbs
##mine live here as files in a directory, MRCAlist.csv is just the names of those files
setwd("~/Desktop/JohnS/probextant/MRCA")
sam<-scan("MRCAlist.csv", what="list", quote=NULL)
for (i in sam) {
  hap36<-read.csv(i)
  hap8<-hap36[,1:3]
  AA<-hap36$AA+(hap36$AB/2)+(hap36$AC/2)+(hap36$AD/2)+(hap36$AE/2)+(hap36$AF/2)+(hap36$AG/2)+(hap36$AH/2)
  BB<-hap36$BB+(hap36$AB/2)+(hap36$BC/2)+(hap36$BD/2)+(hap36$BE/2)+(hap36$BF/2)+(hap36$BG/2)+(hap36$BH/2)
  CC<-hap36$CC+(hap36$AC/2)+(hap36$BC/2)+(hap36$CD/2)+(hap36$CE/2)+(hap36$CF/2)+(hap36$CG/2)+(hap36$CH/2)
  DD<-hap36$DD+(hap36$AD/2)+(hap36$BD/2)+(hap36$CD/2)+(hap36$DE/2)+(hap36$DF/2)+(hap36$DG/2)+(hap36$DH/2)
  EE<-hap36$EE+(hap36$AE/2)+(hap36$BE/2)+(hap36$CE/2)+(hap36$DE/2)+(hap36$EF/2)+(hap36$EG/2)+(hap36$EH/2)
  FF<-hap36$FF+(hap36$AF/2)+(hap36$BF/2)+(hap36$CF/2)+(hap36$DF/2)+(hap36$EF/2)+(hap36$FG/2)+(hap36$FH/2)
  GG<-hap36$GG+(hap36$AG/2)+(hap36$BG/2)+(hap36$CG/2)+(hap36$DG/2)+(hap36$EG/2)+(hap36$FG/2)+(hap36$GH/2)
  HH<-hap36$HH+(hap36$AH/2)+(hap36$BH/2)+(hap36$CH/2)+(hap36$DH/2)+(hap36$EH/2)+(hap36$FH/2)+(hap36$GH/2)
  hap8<-cbind(hap8, AA, BB, CC, DD, EE, FF, GG, HH)
  write.csv(hap8, file=paste("8", i, sep="_"), row.names=FALSE)
  rm(hap8)
  rm(hap36)
  
}


```

```{r}
#Creating the prob array. Only need to do once!
Sam.List<-scan("MRCAlist2.csv", what="list", quote=NULL)

dat1<-read.csv("8_CC001-Uncb38V01.csv")
Snp.Info<-dat1[,1:3]
g.Info<-dat1[,4:11]
gT1<-t(g.Info)

dat2<-read.csv("8_CC002-Uncb38V01.csv")
g.Info<-dat2[,4:11]
gT2<-t(g.Info)

y<-abind(gT1, gT2, along=0)

for( i in 3:length(Sam.List))
{
  a<-Sam.List[[i]]
  g.Info<-read.csv(a)
  g.Info<-g.Info[,4:11]
  gT<-t(g.Info)
  y<-abind(y, gT, along=1)
}

#name the 3 sides of the array
markers<-list(Snp.Info$marker)
haps<-list('A','B','C','D','E','F','G','H')
dimnames(y)[[1]] <- unlist(Sam.List)
dimnames(y)[[2]] <- unlist(haps)
dimnames(y)[[3]] <- unlist(markers)
```

```{r}
#check to see if number of markers, haps, and samples are correct
str(y)
#is the haplotype frequency correct
freqsy <- apply(y, c(1,2), mean)
colMeans(freqsy)

```

```{r}
##traitmapping with CC_color data
color <- read.csv("C:/Users/John/Desktop/mapping/CC_color.csv")
rownames(color) <- color$sample

#using the "fixed map" which removes markers with wrong frequency (chr5 and chr13)
GIGA_snps <- read.csv("C:/Users/John/Desktop/mapping/fixedmap.csv")

```

```{r}
#convert the 3d probs object from the doqtl version to qtl2 version. 
probsy <- probs_doqtl_to_qtl2(probs = y, map = GIGA_snps, chr_column="chromosome", pos_column="position", marker_column="marker")

#reordering the chromosomes, otherwise it goes 1,10,11,..
probsy <- subset(probsy, chr=c(1:19, "X")) 

#covariate is not always needed.
#Needs to be numeric??
addcovar <- subset(color, select=c("Sex"))
rownames(addcovar) <- color$sample

#preparing the phenotype. 
pheno <- as.matrix(color$coatcolor)
rownames(pheno) <- color$sample

#not always necessary to have kinship. Various types to chose, see documentation if interested in learning more.
kinshiploco <- calc_kinship(probsy, type = c("loco"), use_allele_probs=FALSE)
kinshipoverall <- calc_kinship(probsy, type = c("overall"), use_allele_probs=FALSE)

#How heritible is the trait? Can't use LOCO kinship, only overall kinship
est_herit(pheno, kinship = kinshipoverall, addcovar = addcovar)
```

```{r}

#this is the qtl mapping function.
out <- scan1(probsy, pheno=pheno, addcovar=addcovar, kinship = kinshiploco)

#weird, don't use. Sometimes the binary model does some odd things.
#out <- scan1(probsy, pheno=pheno, model="binary")

#Need to change map to rqtl2 friendly version for plotting qtl and allelic effects
map <- map_df_to_list(GIGA_snps, chr_column = "chromosome", pos_column = "position", marker_column = "marker", Xchr = c("X"))

#ploting out QTL
plot(out, map, lodcolumn=1, col="slateblue")
```

```{r}
#scan1blup is the way to show allelic effects. Specify what chromosome you whant to see.
blup2 <- scan1blup(probsy[,"7"], pheno = pheno)
plot_coefCC(x = blup2, map=map, scan1_output = out, add = FALSE,  gap = NULL, top_panel_prop = 0.6, legend ="topleft")

```

```{r}
#Permutation is how we determine significance. I would recommend using at least 1000, however it can take a long time, so for this example I am using 50.
perms = scan1perm(genoprobs= probsy, pheno= pheno, n_perm = 50)
hist(perms)
```

```{r}
#we want to find QTL that meet our significance level (.05). 
thr = summary(perms)
thr

#this can be added to our genomewide QTL plot using abline
plot(out, map, lodcolumn=1, col="slateblue")
abline(h=8.05, col="red")
```

```{r}
#We can find QTL peaks.
peaks = find_peaks(out, map, threshold = thr, prob = 0.95)
peaks

chr<- peaks$chr[1]
start <- peaks$ci_lo
end <- peaks$ci_hi
```

```{r}
#We can do assoc mapping by plotting variants of the eight founder strains using sanger's sequence. THe variants file is quite large.
#pull variant file from here: https://figshare.com/articles/SQLite_database_of_variants_in_Collaborative_Cross_founder_mouse_strains/5280229/2

db <- dbConnect(SQLite(), "C:/Users/John/Desktop/mapping/data/cc_variants.sqlite")
query_variants <- create_variant_query_func(db=db)


assoc = scan1snps(genoprobs = probsy, map = map, pheno = pheno, chr = chr, start = start, end = end, cores = 4, query_func = query_variants, keep_all_snps = TRUE)

plot_snpasso(assoc$lod, assoc$snpinfo)

```

```{r}
#We can also plot genes in our association mapping plot.
#pull gene file from here: https://figshare.com/articles/SQLite_database_with_MGI_mouse_gene_annotations_from_Mouse_Genome_Informatics_MGI_at_The_Jackson_Laboratory/5286019/5

query_genes <- create_gene_query_func("C:/Users/John/Desktop/mapping/data/mouse_genes_mgi.sqlite")

genes <- query_genes(chr = chr, start = start, end = end)

plot_snpasso(assoc$lod, assoc$snpinfo, genes = genes, top_panel_prop = 0.5)
```


#Other things in progress
```{r}
assoc = assoc.map(pheno = pheno, pheno.col = "coatcolor", 
        probs = probsy, K = kinshiploco, snps = genes, chr = 7,
        start = start, end = end, output = "p-value")
assoc.plot(assoc$lod, assoc$snpinfo, genes = genes, top_panel_prop = 0.5)

```




```{r}
#don't have DOQTL??
if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
BiocManager::install("DOQTL")

##Don't have Andrew's packages? go here
library(devtools)
install_github("andrewparkermorgan/argyle")
install.packages("remotes")
remotes::install_github("andrewparkermorgan/mouser")

install.packages("qtl2convert", repos="http://rqtl.org/qtl2cran")

```

```{r}

library(argyle)
library(mouser)

###Sanity check. Does the frequency make sense? For b38 it does not at chr5 and chr13!
## load SNP positions
colnames(Snp.Info) <- c("marker", "chr", "pos")

## take mean across samples to get allele freq at each marker
freqs <- colMeans(y, dims = 1)

## turn it into a dataframe for plotting
freqs2 <- reshape2::melt(freqs, value.name = "freq")
colnames(freqs2)[1:2] <- c("strain","marker")

## add SNP positions
freqs2 <- merge(freqs2, Snp.Info, all.x = TRUE)

## make the plot
ggmanhattan(freqs2) +
  geom_line(aes(y = freq, colour = strain, group = strain:chr)) +
  geom_hline(yintercept = 0.125, lty = "dashed", colour = "darkgrey") +
  scale_y_continuous("allele frequency\n") +
  scale_color_CC() +
  facet_grid(strain ~ .) +
  theme_classic() +
  theme(axis.title.x = element_blank())
```

```{r}
#####So  far not working.....
###need to exclude markers on 5 and 13. 
#SAbGeoEUCOMM001 SAbGeoEUCOMM002
##Beginning near UNC23486670 CH13:118447298 to UNC23498758 CH13:119480991
testy <- y[,, dimnames(y) != "SAbGeoEUCOMM001"]
testy <- y[,, !dimnames(y) %in% c("SAbGeoEUCOMM001")]
testy[,,"SAbGeoEUCOMM001"]


###Lets look at a slice
image(1:ncol(y), 1:78, t(y[78:1,,"SAbGeoEUCOMM001"]), axes = F, ann = F,
      breaks = c(-0.25, 0.25, 0.75, 1.25), col = c("white", "grey50", "black"))
box()
abline(v = 0:9+0.5, col = "grey80")
abline(h = 0:78+0.5, col = "grey80")
mtext(side = 3, line = 0.5, at = 1:8, text = LETTERS[1:8], cex = 1)
mtext(side = 2, line = 0.5, at = 77:1, text = rownames(y)[1:77], las = 1, cex=.5)
title(main ="SAbGeoEUCOMM001")
```
